version: "3"
services:
  doge:
    build: .
  caddy:
    image: caddy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  caddy:

